#!/bin/bash
TMP=$(mktemp -d)
this_test=$1

# delete the cluster
kubash -n $this_test decommission -y
rm -Rf ~/.kubash/clusters/$this_test

# prep for the cluster
envsubst ~/.kubash/examples/$this_test.tpl > $TMP/cluster.yaml
kubash yaml2cluster -n $this_test $TMP/cluster.yaml
rm $TMP/cluster.yaml

# make the cluster
kubash -n $this_test -y provision
kubash -n $this_test --verbosity=105 init

#remove temp
rmdir $TMP
